### ISSUE TITLE
Side-panel should be redesigned for multiple document selection

### ISSUE THREAD

**Issue by StephanH90** [projectcaluma/ember-alexandria#336]
## Summary
The side panel as it is today works relatively well for single document selection. However, for the selection of multiple documents there are some problems. It also produces some UX problems. It is proposed, that the side-panel should be refactored into its own component that is decoupled in its state from the document selection.

## Problems
These are imo the main issues with the side panel today:
1. Closing the document panel works by navigating to the current route and resetting the `document` param. If the `document` or `documents` param is reused for multiple selection this would mean that closing the side bar would deselect all documents. This is pretty poor from a UX point of view.
2. The side panel automatically opens on document selection. In the grid view this means that the documents shuffle around which is bad UX.

## Proposed solution
Decouple the side-bar from the `document` query param and make it its own independent UI component.

This would have the advantages that:
1. users could toggle its state using a button (show/hide)
2. the state of the side panel could be reflected as a url param, ex. `side-panel=true`
3. selecting/deselecting documents does not open/close the side bar repeatedly. Instead the contents of the side-panel get updated to reflect a single document selection or a multiple document selection.

## Ideas
I have started to implement this with a toggle button:
![image](https://user-images.githubusercontent.com/88476449/129052119-eefee892-6bec-43e8-bab2-b0050c7ba18b.png)

## ToDos:
- [x] Refactor and extract the tag manager into its own component to allow it to work for both single and multiple documents

**Comment by czosel** [comment]
This has been implemented.
